package com.leemra.battleship.classic;

import com.leemra.battleship.IController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * Starter class for NewBattleShip application.
 *
 * @author IntelliJ IDEA - AutoGenerated class
 * @see ClassicGameController
 */
public class ClassicBattleShip {
    Application app;

    public ClassicBattleShip(Application app) {
        this.app = app;
    }

    public void run(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(ClassicBattleShip.class.getResource("battleship-classic.fxml"));
            stage.setScene(new Scene(fxmlLoader.load(), 700, 700));
            ((IController) fxmlLoader.getController()).setApp(app);
            stage.getScene().getStylesheets().clear();
            stage.getScene().getStylesheets().add("Styles.css");
            stage.show();
        } catch (IOException ignored) {

        }
    }
}