package edu.gcu.cst120.battleship;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * Starter class for BattleShip application.
 * @author IntelliJ IDEA - AutoGenerated class
 * @see BattleShipController
 */
public class BattleShip extends Application {
	@Override
	public void start(Stage stage) {
		try {
			FXMLLoader fxmlLoader = new FXMLLoader(BattleShip.class.getResource("battleship-view.fxml"));
			Scene scene = new Scene(fxmlLoader.load(), 320, 240);
			stage.setTitle("BattleShip");
			stage.setMinHeight(700);
			stage.setMinWidth(700);
			scene.getStylesheets().add("Styles.css");
			stage.setScene(scene);
			stage.show();
		} catch (IOException ignored) {
		
		}
	}
	
	public static void main(String[] args) {
		launch();
	}
}